In [24]:
import numpy as np

arr = np.array([[1,2,3,4,9], [6,7,8,9,10]])
arr1=arr.flatten()
print(arr1)
arr2=np.sort(arr1)[-1]
print(f"Sorted arra is {arr2}")
# print('Last element from 2nd dim: ', arr[2, -1])
print(type(arr))

[ 1  2  3  4  9  6  7  8  9 10]
Sorted arra is 10
<class 'numpy.ndarray'>


In [34]:
arr1=np.array([1,2,3,4,5])
x=arr1.copy()
arr1[0]=50
print(arr1)
print(x)

[50  2  3  4  5]
[1 2 3 4 5]


In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr=arr.reshape(-1)
print(newarr)
x=arr.view()
arr[0]=50
print(arr)
print(x)


[1 2 3 4 5 6]
[[50 50 50]
 [ 4  5  6]]
[[50 50 50]
 [ 4  5  6]]


In [33]:
arry1=np.array([1,2,3,4,5,6])
print(arry1[::2])

[1 3 5]


In [54]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df) 


dff=pd.read_csv("first.csv")
print(dff)

   calories  duration
0       420        50
1       380        40
2       390        45


FileNotFoundError: [Errno 2] No such file or directory: 'first.csv'

In [50]:
import pandas as pd

df=pd.read_csv("first.csv")
print(df)

FileNotFoundError: [Errno 2] No such file or directory: 'first.csv'

In [44]:
print(df.loc[1])

calories    380
duration     40
Name: 1, dtype: int64
